
# Introduction to Numerical Computing with `Numpy`

<img src="image/numpy-color-image.png" width="800" />

### pip3 install `numpy`

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

In [3]:
arr = np.array([0, 1, 2, 3]) # One-dimensional array
arr

array([0, 1, 2, 3])

In [4]:
# numeric "type" of Elements 
arr.dtype

dtype('int64')

In [5]:
# change array data type 
arr_dtype = np.array(
            [1, 2, 3], 
            dtype= np.float64)
arr_dtype


array([1., 2., 3.])

In [6]:
arr_dtype.dtype

dtype('float64')

In [7]:
#checking the type 
type(arr)

numpy.ndarray

In [8]:
# shape array
arr.shape

(4,)

In [9]:
arr.ndim

1

In [10]:
# Two-dimensional array
arr_2d = np.array(
        [[1, 2, 3],
         [4, 5, 6]])

<img src="image/numpy-matrix24.png" width="300" />

In [11]:
print("2D_array shape: ", arr_2d.shape)
print("Number of rows: ", arr_2d.shape[0], " Number of cols: ", arr_2d.shape[1])
print("Number of dimensions: ", arr_2d.ndim)

2D_array shape:  (2, 3)
Number of rows:  2  Number of cols:  3
Number of dimensions:  2


### `Indexing` array
<img src="image/numpy-matrix-indexing.png" width="600" />

In [12]:
print("first row: ", arr_2d[0])


first row:  [1 2 3]


In [13]:
# Get / Set Elements
print(arr_2d[1 , 2]) # array[ row, column ]

arr_2d[1, 2] = -6
arr_2d

6


array([[ 1,  2,  3],
       [ 4,  5, -6]])

In [14]:
# Sclicing 
print(arr_2d[0 ,1:], "\n")

print(arr_2d[: ,1], "\n" )

print(arr_2d[1 ,0:2] )

[2 3] 

[2 5] 

[4 5]


### `Reshaping` an array
<img src="image/numpy-reshape.png" width="700"/>


In [60]:
print(np.reshape(arr_2d, newshape=(3, 2))) # (2, 3) (1, 6) (6, 1) ---> arr_2d.size = 6

[[ 1  2]
 [ 3  4]
 [ 5 -6]]


In [16]:
arr_2d.size

6

In [17]:
print(np.reshape(arr_2d, (1, -1)))  # -1 means the number of columns will be determined automatically

[[ 1  2  3  4  5 -6]]


In [18]:
print(np.reshape(arr_2d, (-1, 1)))   # -1 means the number of rows will be determined automatically

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [-6]]


### `Transposing` Array
<img src="image/numpy-transpose.png" width="500" />

In [19]:
print(arr_2d)
print()
print(arr_2d.T)

[[ 1  2  3]
 [ 4  5 -6]]

[[ 1  4]
 [ 2  5]
 [ 3 -6]]


### np.arange()

In [20]:
print(np.arange(1, 20, step=2))


[ 1  3  5  7  9 11 13 15 17 19]


### Creating `specific` arrays
- `np.zeros`
- `np.ones`
- `np.full`
- `np.random.random`

<img src="image/numpy-matrix-ones-zeros-random.png" width="800">

In [21]:
print(np.ones(shape=(3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
print(np.zeros(shape=(3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
print(np.full(shape=(3, 2), fill_value=7))

[[7 7]
 [7 7]
 [7 7]]


### Creating `random` arrays


In [24]:
print(np.random.random(size=(3, 2)))

[[0.76767256 0.17242636]
 [0.50217204 0.40957205]
 [0.3549226  0.97899784]]


In [25]:
print(np.random.randn(3, 4))

[[ 0.39666441  2.60410778 -0.31151685  1.53669666]
 [ 0.66288352  0.18553701 -0.14140482 -0.47223123]
 [-0.77263568  1.06867168 -1.28210444  0.40845824]]


<img src="image/Bell-Curve.png" width="400"/>

### Operations on `numpy` arrays
- `np.add`
- `np.subtract`
- `np.multiply`
- `np.divide`
- `np.sqrt`

In [26]:
x = np.array(
        [[2, 4], 
         [1, 5]])

y = np.array(
        [[6, 9],
         [8, 3]])


In [27]:
print("Elementwise sum: \n", np.add(x, y))
print("\nElementwise difference: \n", np.subtract(x, y))
print("\nElementwise product: \n", np.multiply(x, y))
print("\nElementwise division: \n", np.divide(x, y))
print("\nElementwise square: \n ", np.sqrt(y))

Elementwise sum: 
 [[ 8 13]
 [ 9  8]]

Elementwise difference: 
 [[-4 -5]
 [-7  2]]

Elementwise product: 
 [[12 36]
 [ 8 15]]

Elementwise division: 
 [[0.33333333 0.44444444]
 [0.125      1.66666667]]

Elementwise square: 
  [[2.44948974 3.        ]
 [2.82842712 1.73205081]]


### Matrix multiplication in `numpy`


In [28]:
x = np.array([[1, 2,3]])

y = np.array(
        [[4, 5],
         [7, 6],
         [8, 9]])

print(x.dot(y))
print(np.dot(x, y))

[[42 44]]
[[42 44]]


<img src="image/numpy-matrix-dot-product-1.png" width="650" />

### Mathematical and Statistical Function in `numpy`
<img src="image/numpy-array-aggregation.png" width="800" />

In [29]:
x = np.array(
        [[2, 5],
         [1, 7]])


print("max: ",x.max())
print("min: ",x.min())
print("sum: ",x.sum())
print("mean: ",x.mean())
print("std: ",x.std())
print("var: ",x.var())

max:  7
min:  1
sum:  15
mean:  3.75
std:  2.384848003542364
var:  5.6875


### axis
<img src="image/numpy-matrix-aggregation-4.png" width="800" />

In [30]:
print("axis = 0 : ", x.max(axis=0))
print("axis = 1 : ", x.max(axis=1))

axis = 0 :  [2 7]
axis = 1 :  [5 7]


In [31]:
print("axis = 0 : ", x.mean(axis=0))
print("axis = 1 : ", x.sum(axis=1))

axis = 0 :  [1.5 6. ]
axis = 1 :  [7 8]


In [32]:
# logarithm of x
print(np.log([1,2,3])) # base e
print(np.log2(2**3))   # base 2
print(np.log10(10**3)) # base 10

[0.         0.69314718 1.09861229]
3.0
3.0


In [33]:
# exponential ---> e^x = e^2
print(np.exp(2),'\n')
print(np.exp([[1,2],[3,4]]))

7.38905609893065 

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [34]:
# absolute
np.abs([-1, -2, -3])

array([1, 2, 3])

In [35]:
#power 
print("2^3: ", np.power(2,3),"\n")

print(np.power([10,20,30], 2))



2^3:  8 

[100 400 900]


In [36]:
m = np.array([4, 5, 6, 1])
print("indices of the minimum : ",np.argmin(m))
print("indices of the maximum : ",np.argmax(m))

indices of the minimum :  3
indices of the maximum :  2


In [37]:
n = np.array(
            [[4, 5, 6, 1],
            [8, 2, 5, 6]])
print("indices of the minimum : ",np.argmin(n, axis=0))
print("indices of the maximum : ",np.argmax(n, axis=1))

indices of the minimum :  [0 1 1 0]
indices of the maximum :  [2 0]


### Array Broadcasting `numpy`

In [38]:
data = np.array(
                [[1, 2],
                 [3, 4],
                 [5, 6]])
one_row = np.ones(shape=(2,))
data = np.add(data, one_row)
data

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

<img src="image/numpy-matrix-broadcast.png" width="700" />

### 3D Numpy Array

In [70]:
np.random.random((2,3,4))

array([[[0.93699814, 0.96666329, 0.80119314, 0.21709243],
        [0.05656135, 0.62003856, 0.40203426, 0.02808393],
        [0.25221871, 0.51000991, 0.75889247, 0.74066343]],

       [[0.12851187, 0.66810106, 0.86605795, 0.80091259],
        [0.75754776, 0.98279532, 0.97434905, 0.65508282],
        [0.41044399, 0.00868474, 0.29525291, 0.81783941]]])

<img src="image/3D-arrays.png" width="500" />

### Resource 
    1. https://cs231n.github.io/python-numpy-tutorial/
    2. https://realpython.com/tutorials/numpy/
    3. The Basics of NumPy Arrays _ Python Data Science Handbook (Book)